# Dockerfile for cloud face processing container

FROM ubuntu
LABEL Maintainer="Richard Ryu <richard.ryu@berkeley.edu>" \
      Description="cloud face container on ubunutu."

# Install Packages
RUN apt update

ENV DEBIAN_FRONTEND=noninteractive

RUN apt install -y python-pip python-opencv vim-tiny mosquitto-clients libopencv-dev

RUN pip install paho-mqtt

EXPOSE 1883

WORKDIR /
COPY cface.py .
CMD python cface.py

