# Dockerfile for broker container
FROM alpine
LABEL Maintainer="Richard Ryu <richard.ryu@berkeley.edu>" \
      Description="Broker Container on Alpine."

# Install Packages
RUN apk update && apk add mosquitto

EXPOSE 1883

# Running Mosquitto
CMD /usr/sbin/mosquitto
